# Starship config file

# Format
format = """
$all
"""

# Replace symbol
[character]
success_symbol = "[❯❯❯](bold cyan)"
error_symbol = "[❯❯❯](bold purple)"
vicmd_symbol = "[❮❮❮](bold cyan)"

# Line Break
[line_break]
disabled = true

# Directory opts
[directory]
truncation_length = 2
style = "bold blue"

# Disable Command Duration
[cmd_duration]
disabled = true
